"""refactor

Revision ID: 325f1314a06a
Revises: c53ee8e07e6a
Create Date: 2024-05-26 17:19:54.589798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '325f1314a06a'
down_revision = 'c53ee8e07e6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)

    # ### end Alembic commands ###
