"""name field for paste

Revision ID: 51a45e3fb97a
Revises: ffc88474728c
Create Date: 2024-07-06 16:13:07.634963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51a45e3fb97a'
down_revision = 'ffc88474728c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paste', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.String(), nullable=False))
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paste', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.drop_column('filename')

    # ### end Alembic commands ###
