"""paste table

Revision ID: c0d93de9b42b
Revises: 8f61f6dbb6b3
Create Date: 2024-06-04 17:57:48.937935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0d93de9b42b'
down_revision = '8f61f6dbb6b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paste', schema=None) as batch_op:
        batch_op.add_column(sa.Column('line_count', sa.String(), nullable=False))
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paste', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.drop_column('line_count')

    # ### end Alembic commands ###
